name: 'New Relic Github Actions Analytics'
description: 'Stores the result of Github Actions in New Relic for CI/CD pipeline analytics'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  # region:
  #   description: 'Your New Relic account region: US or EU. Defaults to US'
  #   required: false
  #   default: 'US'
  # insert-key:
  #   description: 'New Relic Insights Insert Key - https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/#insights-insert-key'
  #   required: true
  # account-id:
  #   description: 'Your New Relic account ID to send the data to'
  #   required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'
