on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: danifitz/newrelic-action@v0.2
        with:
          who-to-greet: 'Mona the Octocat'
          region: 'US'
          account-id: 2137428
          insert-key: ${{ secrets.INSERT_KEY }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"