on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: danifitz/newrelic-action@v0.9.4
        with:
          region: 'US'
          account-id: 2137428
          insert-key: ${{ secrets.INSERT_KEY }}