on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Echo Hello
        id: echo-hello
        run: echo hello
      - name: Send to New Relic
        id: send-to-new-relic
        uses: danifitz/newrelic-action@v0.9.5
        with:
          region: 'US'
          account-id: 2137428
          insert-key: ${{ secrets.INSERT_KEY }}